import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import App from './frontend/routes/app';
import reducer from './frontend/reducers';

const initialState = {
  "user": {
  },
  "playing": {

  },
  "myList": [
  ],
  "trends": [
    {
      "id": 2,
      "slug": "tvshow-2",
      "title": "In the Dark",
      "type": "Scripted",
      "language": "English",
      "year": 2009,
      "contentRating": "16+",
      "duration": 164,
      "cover": "https://vignette.wikia.nocookie.net/arrow/images/f/f8/Arrow_Season_6_Poster.png/revision/latest?cb=20170930195700&path-prefix=es",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 3,
      "slug": "tvshow-3",
      "title": "Instinct",
      "type": "Adventure",
      "language": "English",
      "year": 2002,
      "contentRating": "16+",
      "duration": 137,
      "cover": "https://pics.filmaffinity.com/Dark_Serie_de_TV-111203947-large.jpg",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 4,
      "slug": "tvshow-4",
      "title": "Grand Hotel",
      "type": "Comedy",
      "language": "English",
      "year": 2014,
      "contentRating": "16+",
      "duration": 163,
      "cover": "https://upload.wikimedia.org/wikipedia/en/e/e1/Vikings_Season_5_Volume_1.png",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 5,
      "slug": "tvshow-5",
      "title": "Stargate Atlantis",
      "type": "Scripted",
      "language": "English",
      "year": 2014,
      "contentRating": "16+",
      "duration": 194,
      "cover": "https://images-na.ssl-images-amazon.com/images/I/81yQcA5Xv%2BL._SL1500_.jpg",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 6,
      "slug": "tvshow-6",
      "title": "Final Space",
      "type": "Scripted",
      "language": "English",
      "year": 2017,
      "contentRating": "16+",
      "duration": 124,
      "cover": "https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 7,
      "slug": "tvshow-7",
      "title": "The InBetween",
      "type": "Drama",
      "language": "English",
      "year": 2011,
      "contentRating": "16+",
      "duration": 179,
      "cover": "https://es.web.img2.acsta.net/pictures/17/09/29/21/15/4233147.jpg",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
  ],
  "originals": [
    {
      "id": 8,
      "slug": "tvshow-8",
      "title": "Stargate Atlantis",
      "type": "Action",
      "language": "English",
      "year": 2012,
      "contentRating": "16+",
      "duration": 148,
      "cover": "https://dummyimage.com/800x600.png/306880/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 9,
      "slug": "tvshow-9",
      "title": "Alien Highway",
      "type": "Action",
      "language": "English",
      "year": 2019,
      "contentRating": "16+",
      "duration": 128,
      "cover": "https://dummyimage.com/800x600.png/604180/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 10,
      "slug": "tvshow-10",
      "title": "Elementary",
      "type": "Animation",
      "language": "English",
      "year": 2011,
      "contentRating": "16+",
      "duration": 346,
      "cover": "https://dummyimage.com/800x600.png/FF91BA/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 11,
      "slug": "tvshow-11",
      "title": "Strange Angel",
      "type": "War",
      "language": "English",
      "year": 2015,
      "contentRating": "16+",
      "duration": 226,
      "cover": "https://dummyimage.com/800x600.png/45807C/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 12,
      "slug": "tvshow-12",
      "title": "Private Eyes",
      "type": "Comedy",
      "language": "English",
      "year": 2018,
      "contentRating": "16+",
      "duration": 190,
      "cover": "https://dummyimage.com/800x600.png/577380/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 13,
      "slug": "tvshow-13",
      "title": "NCIS: Los Angeles",
      "type": "Drama",
      "language": "English",
      "year": 2010,
      "contentRating": "16+",
      "duration": 160,
      "cover": "https://dummyimage.com/800x600.png/5472FF/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 14,
      "slug": "tvshow-13",
      "title": "NCIS: Los Angedddddddddddddddddles",
      "type": "Drama",
      "language": "English",
      "year": 2010,
      "contentRating": "16+",
      "duration": 160,
      "cover": "https://dummyimage.com/800x600.png/5472FF/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
    {
      "id": 15,
      "slug": "tvshow-13",
      "title": "NCIS: Los Angeles",
      "type": "Drama",
      "language": "English",
      "year": 2010,
      "contentRating": "16+",
      "duration": 160,
      "cover": "https://dummyimage.com/800x600.png/5472FF/ffffff",
      "description": "Vestibulum ac est lacinia nisi venenatis tristique",
      "source": "http://mdstrm.com/video/58333e214ad055d208427db5.mp4",
    },
  ],
};
const store = createStore(reducer, initialState);

ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById('app'));
